### ISSUE TITLE
Error on survival placed head break

### ISSUE THREAD

**Issue by Qveshn** [cnaude/TrophyHeads#8]
Every time when any player broke placed head in survival, which not created by the TrophyHeads (decoration head with texture like from HeadDatabase plugin or from command block) this error appeares:
http://pastebin.com/vduPFQir

**Comment by cnaude** [comment]
Please try latest dev version. https://h.cnaude.org/jenkins/job/TrophyHeads/45/

**Comment by Qveshn** [comment]
Thanks, I've already did this. That's works!
